# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a51a30339d6290b12bda8b8501564799c6804f028111e323e66cf2dcd63eb1d19d3c3c7bbe7c3b7aabe95fd7aaf10bb4e48f1a692607071554776b4fea84b86

test:
  secret_key_base: 1cd78e82c4842deed1d1bfc0d093b73c38443d2796c1c4a608aa02b7881c0f78edb0147a64138622ccd979f0f5c7641f768f00e7fab696b8b73534df334165a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
